### PR TITLE
fix stacking of millennial buffs of same type

### LINKED ISSUE #1274: Millennial weapon buffs of the same type should not stack
We currently have 3 weapons from the Millennial weapon series:
- Freedom-Sworn: "Millennial Movement: Song of Resistance" grants NA/CA/Plunging DMG% and ATK%
- Song of Broken Pines: "Millennial Movement: Banner-Hymn" grants NA ATK Speed and ATK%
- Elegy for the End: "Millennial Movement: Farewell Song" grants EM and ATK%

Buffs of the same type within "Millenial Movement" should not stack. This actually just refers to the ATK% buff, since that's the one that's shared between all of them. To fix this we need to introduce a shared key for the ATK% part of the buff called `millennial-common-atk%` (name is just an example).

### PR DESCRIPTION
**Pull request by k0l11**
fixes #1274

### CODE REVIEW

File: internal/weapons/sword/freedom/freedom.go [hunk 1]
```diff
@@ -75,30 +73,29 @@ func NewWeapon(c *core.Core, char *character.CharWrapper, p weapon.WeaponProfile
...
 					},
 				})
 				char.AddAttackMod(character.AttackMod{
-					Base: modifier.NewBaseWithHitlag(atkModKey, 12*60),
+					Base: modifier.NewBaseWithHitlag(common.MillennialKey, buffDuration),
 					Amount: func(atk *combat.AttackEvent, t combat.Target) ([]float64, bool) {
 						switch atk.Info.AttackTag {
 						case combat.AttackTagNormal, combat.AttackTagExtra, combat.AttackTagPlunge:
-							return buffNACAPlunge, true
+							return uniqueVal, true
```
Comment (unleashurgeek) [inline internal/weapons/sword/freedom/freedom.go:98]: flip usage of `sharedVal` and `uniqueVal` (not overwriting the right buff)

**Review by unleashurgeek — APPROVED** [review]
