### PR TITLE
fix albedo q snapshot, a4 and c2 timing

### LINKED ISSUE #1124: Albedo Q Initial should be dynamic
https://docs.google.com/spreadsheets/d/1M2nTLogzYd2o4ZLkYEkzfovwiTznQOB5ujWuMlQbE0k/edit?usp=drivesdk
https://discord.com/channels/845087716541595668/869210750596554772/1046941627530354759

### PR DESCRIPTION
**Pull request by k0l11**
fixes #1124

### CODE REVIEW

File: internal/characters/albedo/burst.go [hunk 1]
```diff
@@ -33,28 +33,55 @@ func (c *char) Burst(p map[string]int) action.ActionInfo {
...
+			})
+		}
+
+		// fatal blossom
+		if !c.skillActive {
+			return
+		}
 		ai.Abil = "Rite of Progeniture: Tectonic Tide (Blossom)"
 		ai.Mult = burstPerBloom[c.TalentLvlBurst()]
+		initialFatalBlossomHitmark := fatalBlossomHitmark - burstHitmark
```
Comment (unleashurgeek) [inline internal/characters/albedo/burst.go:78]: nit: should we just change the value of `fatalBlossomHitmark` instead? (can do `145 - burstHitmark` if we want to keep the current value for posterity)

**Review by unleashurgeek — APPROVED** [review]

File: internal/characters/albedo/burst.go (hunk 1 above)
Comment (k0l11) [reply internal/characters/albedo/burst.go:78]: yeah I'll change that very soon

Comment (k0l11) [reply internal/characters/albedo/burst.go]: done
