### PR TITLE
partially fix kazuha c2 and c6

### LINKED ISSUE #605: kazuha c6 should be added via predamagemod
title

currently:

image

### PR DESCRIPTION
**Pull request by k0l11**
This PR is for improving the implementation of Kazuha's C2 and C6. Even though there are still some uncertainties, I believe this PR will make things more accurate when compared to before. However, this change spams the status log in debug with kazuha-c2 getting refreshed every 0.5s.

Kazuha C6 dmg up part didn't check for normal/charged/plunge and used a custom snapshot function, when it should be dynamic (fixes #605).

for sure:
- C2 ticks every 0.5s to apply the C2 buff to active char and Kazuha for 1s

unsure:
- Q field starts and ends when? assumption: starts on Initial Hit hitlag end and lasts until the last tick (needed for C2)
- C6 starts when? assumption: on E hitmark / Q Initial Hit hitlag end

TODO:
- [ ] update docs after merge

### CODE REVIEW

File: internal/characters/kazuha/cons.go [hunk 1]
```diff
@@ -3,14 +3,56 @@ package kazuha
...
+// The Autumn Whirlwind field created by Kazuha Slash has the following effects:
+// - Increases Kaedehara Kazuha's own Elemental Mastery by 200 for its duration.
+// - Increases the Elemental Mastery of characters within the field by 200.
+// The Elemental Mastery-increasing effects of this Constellation do not stack.
+func (c *char) c2() {
+	// don't tick if Q isn't up anymore
+	if c.Core.Status.Duration(burstStatus) == 0 {
+		return
+	}
+
```
Comment (srliao) [inline internal/characters/kazuha/cons.go:21]: should add a src check here just in case someone manages to reach 50% cdr

**Review by srliao — APPROVED** [review]
